/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminDiagnosticsRouteImport } from './routes/admin/diagnostics'
import { Route as AdminLogsRouteImport } from './routes/admin/logs'
import { Route as AdminPlansRouteImport } from './routes/admin/plans'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSupportRouteImport } from './routes/admin/support'
import { Route as AdminTemplatesRouteImport } from './routes/admin/templates'
import { Route as AdminTenantsRouteImport } from './routes/admin/tenants'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard/analytics'
import { Route as DashboardBranchesRouteImport } from './routes/dashboard/branches'
import { Route as DashboardBrandingRouteImport } from './routes/dashboard/branding'
import { Route as DashboardCatalogRouteImport } from './routes/dashboard/catalog'
import { Route as DashboardCategoriesRouteImport } from './routes/dashboard/categories'
import { Route as DashboardOffersRouteImport } from './routes/dashboard/offers'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard/orders'
import { Route as DashboardPaymentsRouteImport } from './routes/dashboard/payments'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardQrRouteImport } from './routes/dashboard/qr'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardStaffRouteImport } from './routes/dashboard/staff'
import { Route as DashboardSubscriptionRouteImport } from './routes/dashboard/subscription'
import { Route as DashboardSupportRouteImport } from './routes/dashboard/support'
import { Route as DashboardWhatsappRouteImport } from './routes/dashboard/whatsapp'
import { Route as OrderTokenRouteImport } from './routes/order.$token'
import { Route as QTokenRouteImport } from './routes/q.$token'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as RSlugRouteImport } from './routes/r.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as RSlugIndexRouteImport } from './routes/r.$slug/index'
import { Route as RSlugAboutRouteImport } from './routes/r.$slug/about'
import { Route as RSlugCartRouteImport } from './routes/r.$slug/cart'
import { Route as RSlugCheckoutRouteImport } from './routes/r.$slug/checkout'
import { Route as RSlugLocationRouteImport } from './routes/r.$slug/location'
import { Route as RSlugMenuRouteImport } from './routes/r.$slug/menu'
import { Route as RSlugOffersRouteImport } from './routes/r.$slug/offers'
import { Route as RSlugOrderTokenRouteImport } from './routes/r.$slug/order.$token'
import { Route as RSlugProductItemSlugRouteImport } from './routes/r.$slug/product.$itemSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiagnosticsRoute = AdminDiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTemplatesRoute = AdminTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTenantsRoute = AdminTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBranchesRoute = DashboardBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBrandingRoute = DashboardBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCatalogRoute = DashboardCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCategoriesRoute = DashboardCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOffersRoute = DashboardOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPaymentsRoute = DashboardPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardQrRoute = DashboardQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStaffRoute = DashboardStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSubscriptionRoute = DashboardSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSupportRoute = DashboardSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWhatsappRoute = DashboardWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => DashboardRoute,
} as any)
const OrderTokenRoute = OrderTokenRouteImport.update({
  id: '/order/$token',
  path: '/order/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const QTokenRoute = QTokenRouteImport.update({
  id: '/q/$token',
  path: '/q/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RSlugRoute = RSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const RSlugIndexRoute = RSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RSlugRoute,
} as any)
const RSlugAboutRoute = RSlugAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => RSlugRoute,
} as any)
const RSlugCartRoute = RSlugCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => RSlugRoute,
} as any)
const RSlugCheckoutRoute = RSlugCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => RSlugRoute,
} as any)
const RSlugLocationRoute = RSlugLocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => RSlugRoute,
} as any)
const RSlugMenuRoute = RSlugMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => RSlugRoute,
} as any)
const RSlugOffersRoute = RSlugOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => RSlugRoute,
} as any)
const RSlugOrderTokenRoute = RSlugOrderTokenRouteImport.update({
  id: '/order/$token',
  path: '/order/$token',
  getParentRoute: () => RSlugRoute,
} as any)
const RSlugProductItemSlugRoute = RSlugProductItemSlugRouteImport.update({
  id: '/product/$itemSlug',
  path: '/product/$itemSlug',
  getParentRoute: () => RSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/demo': typeof DemoRoute
  '/industries': typeof IndustriesRoute
  '/login': typeof LoginRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/solutions': typeof SolutionsRoute
  '/admin/diagnostics': typeof AdminDiagnosticsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/branches': typeof DashboardBranchesRoute
  '/dashboard/branding': typeof DashboardBrandingRoute
  '/dashboard/catalog': typeof DashboardCatalogRoute
  '/dashboard/categories': typeof DashboardCategoriesRoute
  '/dashboard/offers': typeof DashboardOffersRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/qr': typeof DashboardQrRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/staff': typeof DashboardStaffRoute
  '/dashboard/subscription': typeof DashboardSubscriptionRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/whatsapp': typeof DashboardWhatsappRoute
  '/order/$token': typeof OrderTokenRoute
  '/q/$token': typeof QTokenRoute
  '/join/$token': typeof JoinTokenRoute
  '/r/$slug': typeof RSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/r/$slug/about': typeof RSlugAboutRoute
  '/r/$slug/cart': typeof RSlugCartRoute
  '/r/$slug/checkout': typeof RSlugCheckoutRoute
  '/r/$slug/location': typeof RSlugLocationRoute
  '/r/$slug/menu': typeof RSlugMenuRoute
  '/r/$slug/offers': typeof RSlugOffersRoute
  '/r/$slug/': typeof RSlugIndexRoute
  '/r/$slug/order/$token': typeof RSlugOrderTokenRoute
  '/r/$slug/product/$itemSlug': typeof RSlugProductItemSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/industries': typeof IndustriesRoute
  '/login': typeof LoginRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/solutions': typeof SolutionsRoute
  '/admin/diagnostics': typeof AdminDiagnosticsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/branches': typeof DashboardBranchesRoute
  '/dashboard/branding': typeof DashboardBrandingRoute
  '/dashboard/catalog': typeof DashboardCatalogRoute
  '/dashboard/categories': typeof DashboardCategoriesRoute
  '/dashboard/offers': typeof DashboardOffersRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/qr': typeof DashboardQrRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/staff': typeof DashboardStaffRoute
  '/dashboard/subscription': typeof DashboardSubscriptionRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/whatsapp': typeof DashboardWhatsappRoute
  '/order/$token': typeof OrderTokenRoute
  '/q/$token': typeof QTokenRoute
  '/join/$token': typeof JoinTokenRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/r/$slug/about': typeof RSlugAboutRoute
  '/r/$slug/cart': typeof RSlugCartRoute
  '/r/$slug/checkout': typeof RSlugCheckoutRoute
  '/r/$slug/location': typeof RSlugLocationRoute
  '/r/$slug/menu': typeof RSlugMenuRoute
  '/r/$slug/offers': typeof RSlugOffersRoute
  '/r/$slug': typeof RSlugIndexRoute
  '/r/$slug/order/$token': typeof RSlugOrderTokenRoute
  '/r/$slug/product/$itemSlug': typeof RSlugProductItemSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/demo': typeof DemoRoute
  '/industries': typeof IndustriesRoute
  '/login': typeof LoginRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/solutions': typeof SolutionsRoute
  '/admin/diagnostics': typeof AdminDiagnosticsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/branches': typeof DashboardBranchesRoute
  '/dashboard/branding': typeof DashboardBrandingRoute
  '/dashboard/catalog': typeof DashboardCatalogRoute
  '/dashboard/categories': typeof DashboardCategoriesRoute
  '/dashboard/offers': typeof DashboardOffersRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/qr': typeof DashboardQrRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/staff': typeof DashboardStaffRoute
  '/dashboard/subscription': typeof DashboardSubscriptionRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/whatsapp': typeof DashboardWhatsappRoute
  '/order/$token': typeof OrderTokenRoute
  '/q/$token': typeof QTokenRoute
  '/join/$token': typeof JoinTokenRoute
  '/r/$slug': typeof RSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/r/$slug/about': typeof RSlugAboutRoute
  '/r/$slug/cart': typeof RSlugCartRoute
  '/r/$slug/checkout': typeof RSlugCheckoutRoute
  '/r/$slug/location': typeof RSlugLocationRoute
  '/r/$slug/menu': typeof RSlugMenuRoute
  '/r/$slug/offers': typeof RSlugOffersRoute
  '/r/$slug/': typeof RSlugIndexRoute
  '/r/$slug/order/$token': typeof RSlugOrderTokenRoute
  '/r/$slug/product/$itemSlug': typeof RSlugProductItemSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/dashboard'
    | '/demo'
    | '/industries'
    | '/login'
    | '/platform'
    | '/pricing'
    | '/solutions'
    | '/admin/diagnostics'
    | '/admin/logs'
    | '/admin/plans'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/templates'
    | '/admin/tenants'
    | '/dashboard/analytics'
    | '/dashboard/branches'
    | '/dashboard/branding'
    | '/dashboard/catalog'
    | '/dashboard/categories'
    | '/dashboard/offers'
    | '/dashboard/orders'
    | '/dashboard/payments'
    | '/dashboard/profile'
    | '/dashboard/qr'
    | '/dashboard/settings'
    | '/dashboard/staff'
    | '/dashboard/subscription'
    | '/dashboard/support'
    | '/dashboard/whatsapp'
    | '/order/$token'
    | '/q/$token'
    | '/join/$token'
    | '/r/$slug'
    | '/admin/'
    | '/dashboard/'
    | '/api/auth/$'
    | '/r/$slug/about'
    | '/r/$slug/cart'
    | '/r/$slug/checkout'
    | '/r/$slug/location'
    | '/r/$slug/menu'
    | '/r/$slug/offers'
    | '/r/$slug/'
    | '/r/$slug/order/$token'
    | '/r/$slug/product/$itemSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/demo'
    | '/industries'
    | '/login'
    | '/platform'
    | '/pricing'
    | '/solutions'
    | '/admin/diagnostics'
    | '/admin/logs'
    | '/admin/plans'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/templates'
    | '/admin/tenants'
    | '/dashboard/analytics'
    | '/dashboard/branches'
    | '/dashboard/branding'
    | '/dashboard/catalog'
    | '/dashboard/categories'
    | '/dashboard/offers'
    | '/dashboard/orders'
    | '/dashboard/payments'
    | '/dashboard/profile'
    | '/dashboard/qr'
    | '/dashboard/settings'
    | '/dashboard/staff'
    | '/dashboard/subscription'
    | '/dashboard/support'
    | '/dashboard/whatsapp'
    | '/order/$token'
    | '/q/$token'
    | '/join/$token'
    | '/admin'
    | '/dashboard'
    | '/api/auth/$'
    | '/r/$slug/about'
    | '/r/$slug/cart'
    | '/r/$slug/checkout'
    | '/r/$slug/location'
    | '/r/$slug/menu'
    | '/r/$slug/offers'
    | '/r/$slug'
    | '/r/$slug/order/$token'
    | '/r/$slug/product/$itemSlug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/dashboard'
    | '/demo'
    | '/industries'
    | '/login'
    | '/platform'
    | '/pricing'
    | '/solutions'
    | '/admin/diagnostics'
    | '/admin/logs'
    | '/admin/plans'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/templates'
    | '/admin/tenants'
    | '/dashboard/analytics'
    | '/dashboard/branches'
    | '/dashboard/branding'
    | '/dashboard/catalog'
    | '/dashboard/categories'
    | '/dashboard/offers'
    | '/dashboard/orders'
    | '/dashboard/payments'
    | '/dashboard/profile'
    | '/dashboard/qr'
    | '/dashboard/settings'
    | '/dashboard/staff'
    | '/dashboard/subscription'
    | '/dashboard/support'
    | '/dashboard/whatsapp'
    | '/order/$token'
    | '/q/$token'
    | '/join/$token'
    | '/r/$slug'
    | '/admin/'
    | '/dashboard/'
    | '/api/auth/$'
    | '/r/$slug/about'
    | '/r/$slug/cart'
    | '/r/$slug/checkout'
    | '/r/$slug/location'
    | '/r/$slug/menu'
    | '/r/$slug/offers'
    | '/r/$slug/'
    | '/r/$slug/order/$token'
    | '/r/$slug/product/$itemSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DemoRoute: typeof DemoRoute
  IndustriesRoute: typeof IndustriesRoute
  LoginRoute: typeof LoginRoute
  PlatformRoute: typeof PlatformRoute
  PricingRoute: typeof PricingRoute
  SolutionsRoute: typeof SolutionsRoute
  OrderTokenRoute: typeof OrderTokenRoute
  QTokenRoute: typeof QTokenRoute
  JoinTokenRoute: typeof JoinTokenRoute
  RSlugRoute: typeof RSlugRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/diagnostics': {
      id: '/admin/diagnostics'
      path: '/diagnostics'
      fullPath: '/admin/diagnostics'
      preLoaderRoute: typeof AdminDiagnosticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/templates': {
      id: '/admin/templates'
      path: '/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AdminTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tenants': {
      id: '/admin/tenants'
      path: '/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AdminTenantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/branches': {
      id: '/dashboard/branches'
      path: '/branches'
      fullPath: '/dashboard/branches'
      preLoaderRoute: typeof DashboardBranchesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/branding': {
      id: '/dashboard/branding'
      path: '/branding'
      fullPath: '/dashboard/branding'
      preLoaderRoute: typeof DashboardBrandingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/catalog': {
      id: '/dashboard/catalog'
      path: '/catalog'
      fullPath: '/dashboard/catalog'
      preLoaderRoute: typeof DashboardCatalogRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/categories': {
      id: '/dashboard/categories'
      path: '/categories'
      fullPath: '/dashboard/categories'
      preLoaderRoute: typeof DashboardCategoriesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/offers': {
      id: '/dashboard/offers'
      path: '/offers'
      fullPath: '/dashboard/offers'
      preLoaderRoute: typeof DashboardOffersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/payments': {
      id: '/dashboard/payments'
      path: '/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof DashboardPaymentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/qr': {
      id: '/dashboard/qr'
      path: '/qr'
      fullPath: '/dashboard/qr'
      preLoaderRoute: typeof DashboardQrRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/staff': {
      id: '/dashboard/staff'
      path: '/staff'
      fullPath: '/dashboard/staff'
      preLoaderRoute: typeof DashboardStaffRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/subscription': {
      id: '/dashboard/subscription'
      path: '/subscription'
      fullPath: '/dashboard/subscription'
      preLoaderRoute: typeof DashboardSubscriptionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/support': {
      id: '/dashboard/support'
      path: '/support'
      fullPath: '/dashboard/support'
      preLoaderRoute: typeof DashboardSupportRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/whatsapp': {
      id: '/dashboard/whatsapp'
      path: '/whatsapp'
      fullPath: '/dashboard/whatsapp'
      preLoaderRoute: typeof DashboardWhatsappRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/order/$token': {
      id: '/order/$token'
      path: '/order/$token'
      fullPath: '/order/$token'
      preLoaderRoute: typeof OrderTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/q/$token': {
      id: '/q/$token'
      path: '/q/$token'
      fullPath: '/q/$token'
      preLoaderRoute: typeof QTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$slug/': {
      id: '/r/$slug/'
      path: '/'
      fullPath: '/r/$slug/'
      preLoaderRoute: typeof RSlugIndexRouteImport
      parentRoute: typeof RSlugRoute
    }
    '/r/$slug/about': {
      id: '/r/$slug/about'
      path: '/about'
      fullPath: '/r/$slug/about'
      preLoaderRoute: typeof RSlugAboutRouteImport
      parentRoute: typeof RSlugRoute
    }
    '/r/$slug/cart': {
      id: '/r/$slug/cart'
      path: '/cart'
      fullPath: '/r/$slug/cart'
      preLoaderRoute: typeof RSlugCartRouteImport
      parentRoute: typeof RSlugRoute
    }
    '/r/$slug/checkout': {
      id: '/r/$slug/checkout'
      path: '/checkout'
      fullPath: '/r/$slug/checkout'
      preLoaderRoute: typeof RSlugCheckoutRouteImport
      parentRoute: typeof RSlugRoute
    }
    '/r/$slug/location': {
      id: '/r/$slug/location'
      path: '/location'
      fullPath: '/r/$slug/location'
      preLoaderRoute: typeof RSlugLocationRouteImport
      parentRoute: typeof RSlugRoute
    }
    '/r/$slug/menu': {
      id: '/r/$slug/menu'
      path: '/menu'
      fullPath: '/r/$slug/menu'
      preLoaderRoute: typeof RSlugMenuRouteImport
      parentRoute: typeof RSlugRoute
    }
    '/r/$slug/offers': {
      id: '/r/$slug/offers'
      path: '/offers'
      fullPath: '/r/$slug/offers'
      preLoaderRoute: typeof RSlugOffersRouteImport
      parentRoute: typeof RSlugRoute
    }
    '/r/$slug/order/$token': {
      id: '/r/$slug/order/$token'
      path: '/order/$token'
      fullPath: '/r/$slug/order/$token'
      preLoaderRoute: typeof RSlugOrderTokenRouteImport
      parentRoute: typeof RSlugRoute
    }
    '/r/$slug/product/$itemSlug': {
      id: '/r/$slug/product/$itemSlug'
      path: '/product/$itemSlug'
      fullPath: '/r/$slug/product/$itemSlug'
      preLoaderRoute: typeof RSlugProductItemSlugRouteImport
      parentRoute: typeof RSlugRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDiagnosticsRoute: typeof AdminDiagnosticsRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminPlansRoute: typeof AdminPlansRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminTemplatesRoute: typeof AdminTemplatesRoute
  AdminTenantsRoute: typeof AdminTenantsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDiagnosticsRoute: AdminDiagnosticsRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminPlansRoute: AdminPlansRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminTemplatesRoute: AdminTemplatesRoute,
  AdminTenantsRoute: AdminTenantsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardBranchesRoute: typeof DashboardBranchesRoute
  DashboardBrandingRoute: typeof DashboardBrandingRoute
  DashboardCatalogRoute: typeof DashboardCatalogRoute
  DashboardCategoriesRoute: typeof DashboardCategoriesRoute
  DashboardOffersRoute: typeof DashboardOffersRoute
  DashboardOrdersRoute: typeof DashboardOrdersRoute
  DashboardPaymentsRoute: typeof DashboardPaymentsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardQrRoute: typeof DashboardQrRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardStaffRoute: typeof DashboardStaffRoute
  DashboardSubscriptionRoute: typeof DashboardSubscriptionRoute
  DashboardSupportRoute: typeof DashboardSupportRoute
  DashboardWhatsappRoute: typeof DashboardWhatsappRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardBranchesRoute: DashboardBranchesRoute,
  DashboardBrandingRoute: DashboardBrandingRoute,
  DashboardCatalogRoute: DashboardCatalogRoute,
  DashboardCategoriesRoute: DashboardCategoriesRoute,
  DashboardOffersRoute: DashboardOffersRoute,
  DashboardOrdersRoute: DashboardOrdersRoute,
  DashboardPaymentsRoute: DashboardPaymentsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardQrRoute: DashboardQrRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardStaffRoute: DashboardStaffRoute,
  DashboardSubscriptionRoute: DashboardSubscriptionRoute,
  DashboardSupportRoute: DashboardSupportRoute,
  DashboardWhatsappRoute: DashboardWhatsappRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface RSlugRouteChildren {
  RSlugAboutRoute: typeof RSlugAboutRoute
  RSlugCartRoute: typeof RSlugCartRoute
  RSlugCheckoutRoute: typeof RSlugCheckoutRoute
  RSlugLocationRoute: typeof RSlugLocationRoute
  RSlugMenuRoute: typeof RSlugMenuRoute
  RSlugOffersRoute: typeof RSlugOffersRoute
  RSlugIndexRoute: typeof RSlugIndexRoute
  RSlugOrderTokenRoute: typeof RSlugOrderTokenRoute
  RSlugProductItemSlugRoute: typeof RSlugProductItemSlugRoute
}

const RSlugRouteChildren: RSlugRouteChildren = {
  RSlugAboutRoute: RSlugAboutRoute,
  RSlugCartRoute: RSlugCartRoute,
  RSlugCheckoutRoute: RSlugCheckoutRoute,
  RSlugLocationRoute: RSlugLocationRoute,
  RSlugMenuRoute: RSlugMenuRoute,
  RSlugOffersRoute: RSlugOffersRoute,
  RSlugIndexRoute: RSlugIndexRoute,
  RSlugOrderTokenRoute: RSlugOrderTokenRoute,
  RSlugProductItemSlugRoute: RSlugProductItemSlugRoute,
}

const RSlugRouteWithChildren = RSlugRoute._addFileChildren(RSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DemoRoute: DemoRoute,
  IndustriesRoute: IndustriesRoute,
  LoginRoute: LoginRoute,
  PlatformRoute: PlatformRoute,
  PricingRoute: PricingRoute,
  SolutionsRoute: SolutionsRoute,
  OrderTokenRoute: OrderTokenRoute,
  QTokenRoute: QTokenRoute,
  JoinTokenRoute: JoinTokenRoute,
  RSlugRoute: RSlugRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
